name: seb_team6
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0
  firebase_messaging: ^16.3.0
  intl: ^0.20.2
  crypto: ^3.0.3
  path_provider: ^2.0.15
  share_plus: ^13.1.0
  pdf: ^3.10.1
  printing: ^5.14.2
  excel: ^2.0.0
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    