// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEfdIg9CMCJdt3ye8dueA-hk3xvyzKXA4',
    appId: '1:672073999518:ios:e7961957fa8c314052078f',
    messagingSenderId: '672073999518',
    projectId: 'laundryin-73d4f',
    storageBucket: 'laundryin-73d4f.firebasestorage.app',
    iosBundleId: 'com.example.sebTeam6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEfdIg9CMCJdt3ye8dueA-hk3xvyzKXA4',
    appId: '1:672073999518:ios:e7961957fa8c314052078f',
    messagingSenderId: '672073999518',
    projectId: 'laundryin-73d4f',
    storageBucket: 'laundryin-73d4f.firebasestorage.app',
    iosBundleId: 'com.example.sebTeam6',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtENJYWxZXSaNj6-hO_nyM1Vjg9wFYxAI',
    appId: '1:672073999518:web:34e377bcdfbb7dc052078f',
    messagingSenderId: '672073999518',
    projectId: 'laundryin-73d4f',
    authDomain: 'laundryin-73d4f.firebaseapp.com',
    storageBucket: 'laundryin-73d4f.firebasestorage.app',
    measurementId: 'G-RX55QXZ7K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-POaVm3EPr_knvqCDGTGS6CHERcteA0',
    appId: '1:672073999518:android:703def7c9bd4230652078f',
    messagingSenderId: '672073999518',
    projectId: 'laundryin-73d4f',
    storageBucket: 'laundryin-73d4f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtENJYWxZXSaNj6-hO_nyM1Vjg9wFYxAI',
    appId: '1:672073999518:web:e7b51175e399e44252078f',
    messagingSenderId: '672073999518',
    projectId: 'laundryin-73d4f',
    authDomain: 'laundryin-73d4f.firebaseapp.com',
    storageBucket: 'laundryin-73d4f.firebasestorage.app',
    measurementId: 'G-WDMTVX5KHZ',
  );

}